[package]
name = "fileflow-scheduler"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
fileflow-domain = { path = "../fileflow-domain" }
serde.workspace = true
sysinfo.workspace = true
tokio.workspace = true
dashmap.workspace = true
thiserror.workspace = true
tokio-util.workspace = true
